-- Invite-only beta requests. No browser policy is defined: the public form goes
-- through the rate-limited Fastify API and all review/invite actions stay admin-only.
create table if not exists public.access_requests (
  id         bigint generated by default as identity primary key,
  email      text not null unique,
  name       text,
  use_case   text,
  source     text not null default 'landing',
  status     text not null default 'pending'
               check (status in ('pending', 'invited', 'accepted', 'declined')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.access_requests enable row level security;
create index if not exists access_requests_status_created_idx
  on public.access_requests (status, created_at desc);
